// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai: ai.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly cards: cards.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai = new ai.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.cards = new cards.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { chat as api_ai_chat_chat } from "~backend/ai/chat";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.chat = this.chat.bind(this)
        }

        /**
         * Processes user queries about credit card optimization and cashback strategies.
         */
        public async chat(params: RequestType<typeof api_ai_chat_chat>): Promise<ResponseType<typeof api_ai_chat_chat>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/chat`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_chat_chat>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { login as api_auth_login_login } from "~backend/auth/login";
import { oauth as api_auth_oauth_oauth } from "~backend/auth/oauth";
import { register as api_auth_register_register } from "~backend/auth/register";
import {
    forgotPassword as api_auth_reset_password_forgotPassword,
    resetPassword as api_auth_reset_password_resetPassword
} from "~backend/auth/reset_password";
import { verifyToken as api_auth_verify_verifyToken } from "~backend/auth/verify";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.forgotPassword = this.forgotPassword.bind(this)
            this.login = this.login.bind(this)
            this.oauth = this.oauth.bind(this)
            this.register = this.register.bind(this)
            this.resetPassword = this.resetPassword.bind(this)
            this.verifyToken = this.verifyToken.bind(this)
        }

        /**
         * Initiates password reset process by sending reset token.
         */
        public async forgotPassword(params: RequestType<typeof api_auth_reset_password_forgotPassword>): Promise<ResponseType<typeof api_auth_reset_password_forgotPassword>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/forgot-password`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_reset_password_forgotPassword>
        }

        /**
         * Authenticates a user with email and password.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Authenticates or creates a user via OAuth (Google/Apple).
         */
        public async oauth(params: RequestType<typeof api_auth_oauth_oauth>): Promise<ResponseType<typeof api_auth_oauth_oauth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/oauth`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_oauth_oauth>
        }

        /**
         * Creates a new user account with email and password.
         */
        public async register(params: RequestType<typeof api_auth_register_register>): Promise<ResponseType<typeof api_auth_register_register>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/register`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_register_register>
        }

        /**
         * Resets user password using reset token.
         */
        public async resetPassword(params: RequestType<typeof api_auth_reset_password_resetPassword>): Promise<ResponseType<typeof api_auth_reset_password_resetPassword>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/reset-password`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_reset_password_resetPassword>
        }

        /**
         * Verifies JWT token and returns user information.
         */
        public async verifyToken(params: RequestType<typeof api_auth_verify_verifyToken>): Promise<ResponseType<typeof api_auth_verify_verifyToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/verify`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_verify_verifyToken>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addCard as api_cards_add_card_addCard } from "~backend/cards/add_card";
import {
    getCardDetails as api_cards_comprehensive_getCardDetails,
    getComprehensiveCards as api_cards_comprehensive_getComprehensiveCards
} from "~backend/cards/comprehensive";
import { fetchCardData as api_cards_external_api_fetchCardData } from "~backend/cards/external_api";
import { list as api_cards_list_list } from "~backend/cards/list";
import {
    activateMerchantOffer as api_cards_merchant_offers_activateMerchantOffer,
    getRelevantOffers as api_cards_merchant_offers_getRelevantOffers,
    getUserMerchantOffers as api_cards_merchant_offers_getUserMerchantOffers,
    markOfferAsUsed as api_cards_merchant_offers_markOfferAsUsed,
    syncMerchantOffers as api_cards_merchant_offers_syncMerchantOffers
} from "~backend/cards/merchant_offers";
import {
    addToPortfolio as api_cards_portfolio_addToPortfolio,
    getUserPortfolio as api_cards_portfolio_getUserPortfolio,
    removeFromPortfolio as api_cards_portfolio_removeFromPortfolio,
    updatePortfolioCard as api_cards_portfolio_updatePortfolioCard
} from "~backend/cards/portfolio";
import { recommend as api_cards_recommend_recommend } from "~backend/cards/recommend";
import { search as api_cards_search_search } from "~backend/cards/search";

export namespace cards {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.activateMerchantOffer = this.activateMerchantOffer.bind(this)
            this.addCard = this.addCard.bind(this)
            this.addToPortfolio = this.addToPortfolio.bind(this)
            this.fetchCardData = this.fetchCardData.bind(this)
            this.getCardDetails = this.getCardDetails.bind(this)
            this.getComprehensiveCards = this.getComprehensiveCards.bind(this)
            this.getRelevantOffers = this.getRelevantOffers.bind(this)
            this.getUserMerchantOffers = this.getUserMerchantOffers.bind(this)
            this.getUserPortfolio = this.getUserPortfolio.bind(this)
            this.list = this.list.bind(this)
            this.markOfferAsUsed = this.markOfferAsUsed.bind(this)
            this.recommend = this.recommend.bind(this)
            this.removeFromPortfolio = this.removeFromPortfolio.bind(this)
            this.search = this.search.bind(this)
            this.syncMerchantOffers = this.syncMerchantOffers.bind(this)
            this.updatePortfolioCard = this.updatePortfolioCard.bind(this)
        }

        /**
         * Activates a merchant offer.
         */
        public async activateMerchantOffer(params: { userId: string, offerId: number }): Promise<ResponseType<typeof api_cards_merchant_offers_activateMerchantOffer>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/merchant-offers/${encodeURIComponent(params.userId)}/${encodeURIComponent(params.offerId)}/activate`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_merchant_offers_activateMerchantOffer>
        }

        /**
         * Adds a card to the database or returns existing card with updated image.
         */
        public async addCard(params: RequestType<typeof api_cards_add_card_addCard>): Promise<ResponseType<typeof api_cards_add_card_addCard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/add`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_add_card_addCard>
        }

        /**
         * Adds a card to user's portfolio.
         */
        public async addToPortfolio(params: RequestType<typeof api_cards_portfolio_addToPortfolio>): Promise<ResponseType<typeof api_cards_portfolio_addToPortfolio>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                cardId:      params.cardId,
                creditLimit: params.creditLimit,
                nickname:    params.nickname,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/portfolio/${encodeURIComponent(params.userId)}/add`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_portfolio_addToPortfolio>
        }

        /**
         * Fetches card data from RewardsCC API.
         */
        public async fetchCardData(params: RequestType<typeof api_cards_external_api_fetchCardData>): Promise<ResponseType<typeof api_cards_external_api_fetchCardData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/fetch-external`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_external_api_fetchCardData>
        }

        /**
         * Retrieves detailed information for a specific card.
         */
        public async getCardDetails(params: { cardId: number }): Promise<ResponseType<typeof api_cards_comprehensive_getCardDetails>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/comprehensive/${encodeURIComponent(params.cardId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_comprehensive_getCardDetails>
        }

        /**
         * Retrieves comprehensive credit card database with advanced filtering.
         */
        public async getComprehensiveCards(params: RequestType<typeof api_cards_comprehensive_getComprehensiveCards>): Promise<ResponseType<typeof api_cards_comprehensive_getComprehensiveCards>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:     params.category,
                issuer:       params.issuer,
                limit:        params.limit === undefined ? undefined : String(params.limit),
                maxAnnualFee: params.maxAnnualFee === undefined ? undefined : String(params.maxAnnualFee),
                minCashback:  params.minCashback === undefined ? undefined : String(params.minCashback),
                network:      params.network,
                offset:       params.offset === undefined ? undefined : String(params.offset),
                query:        params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/comprehensive`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_comprehensive_getComprehensiveCards>
        }

        /**
         * Gets relevant merchant offers for a category.
         */
        public async getRelevantOffers(params: { userId: string, category: string }): Promise<ResponseType<typeof api_cards_merchant_offers_getRelevantOffers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/merchant-offers/${encodeURIComponent(params.userId)}/category/${encodeURIComponent(params.category)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_merchant_offers_getRelevantOffers>
        }

        /**
         * Retrieves user's merchant offers.
         */
        public async getUserMerchantOffers(params: { userId: string }): Promise<ResponseType<typeof api_cards_merchant_offers_getUserMerchantOffers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/merchant-offers/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_merchant_offers_getUserMerchantOffers>
        }

        /**
         * Retrieves user's card portfolio.
         */
        public async getUserPortfolio(params: { userId: string }): Promise<ResponseType<typeof api_cards_portfolio_getUserPortfolio>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/portfolio/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_portfolio_getUserPortfolio>
        }

        /**
         * Retrieves all available credit cards with their cashback categories.
         */
        public async list(): Promise<ResponseType<typeof api_cards_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_list_list>
        }

        /**
         * Marks a merchant offer as used.
         */
        public async markOfferAsUsed(params: { userId: string, offerId: number }): Promise<ResponseType<typeof api_cards_merchant_offers_markOfferAsUsed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/merchant-offers/${encodeURIComponent(params.userId)}/${encodeURIComponent(params.offerId)}/use`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_merchant_offers_markOfferAsUsed>
        }

        /**
         * Recommends the best credit cards for a specific spending category.
         */
        public async recommend(params: RequestType<typeof api_cards_recommend_recommend>): Promise<ResponseType<typeof api_cards_recommend_recommend>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category,
                userId:   params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/recommend`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_recommend_recommend>
        }

        /**
         * Removes a card from user's portfolio.
         */
        public async removeFromPortfolio(params: { userId: string, portfolioId: number }): Promise<ResponseType<typeof api_cards_portfolio_removeFromPortfolio>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/portfolio/${encodeURIComponent(params.userId)}/${encodeURIComponent(params.portfolioId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_portfolio_removeFromPortfolio>
        }

        /**
         * Searches for credit cards by name or issuer.
         */
        public async search(params: RequestType<typeof api_cards_search_search>): Promise<ResponseType<typeof api_cards_search_search>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                query: params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_search_search>
        }

        /**
         * Syncs merchant offers from browser extension.
         */
        public async syncMerchantOffers(params: RequestType<typeof api_cards_merchant_offers_syncMerchantOffers>): Promise<ResponseType<typeof api_cards_merchant_offers_syncMerchantOffers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/merchant-offers/sync`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_merchant_offers_syncMerchantOffers>
        }

        /**
         * Updates a card in user's portfolio.
         */
        public async updatePortfolioCard(params: RequestType<typeof api_cards_portfolio_updatePortfolioCard>): Promise<ResponseType<typeof api_cards_portfolio_updatePortfolioCard>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                creditLimit:    params.creditLimit,
                currentBalance: params.currentBalance,
                isActive:       params.isActive,
                nickname:       params.nickname,
                portfolioId:    params.portfolioId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/portfolio/${encodeURIComponent(params.userId)}/update`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_portfolio_updatePortfolioCard>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
